name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Shivam-8200
          outputs: github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git add .
          git commit -m "Updated snake contribution graph"
          git push
